app/blueprints/core/models.py
from app.app import db
from app.blueprints.auth.models import User


class Categories(db.Model):
    __tablename__ = "Categories"
    
    id = db.Column(db.Integer, primary_key = True)
    userID = db.Column(db.Integer, db.ForeignKey(User.id), nullable = False)
    name = db.Column(db.String, nullable = False)
    budget = db.Column(db.Integer, nullable = False)
    spent = db.Column(db.Integer, nullable = False)
    remaining = db.Column(db.Integer, nullable = False)
    
    def __repr__(self):
        return f"Category Name: {self.name}, Associated UserID: {self.userID}, Budget Allocated: Rs.{self.budget}, Spent Amount: {self.spent}, Remaining amount: {self.remaining}."
    
    def getCategoryID(self):
        return self.id
        

app/blueprints/core/routes.py
from flask import (
    Blueprint,
    render_template,
    Flask,
    request as req,
    redirect,
    url_for,
)
from flask import jsonify, flash

# Import DB and DB Models
from app.app import db, bcrypt
from app.blueprints.core.models import Categories
from app.blueprints.auth.models import User

# Import Authentication modules from flask_login
from flask_login import login_user, logout_user, current_user, login_required

core = Blueprint("core", __name__)




















# ------------------------
# Main App Routes
# ------------------------
@core.route("/")  # /app
@login_required
def index():
    return render_template("/core/index.html", user=current_user)
















# ------------------------
# Budget Allocator Routes
# ------------------------

@core.route("add", methods=["GET", "POST"])
@login_required
def add():
    if req.method == "GET":
        return render_template("/core/add.html")
    elif req.method == "POST":
        cash = req.form.get("cash")
        newBalance = int(cash) + int(current_user.balance)
        # current_user directly Refers to that Row, if we change values for current_user and commit to DB,
        # the changes take effect in the main Database as well. It represents a "LIVE row in the DB, not just a copy"
        # Even though current_user "refers to that row," the changes only hit the main database file when you call db.session.commit().
        current_user.balance = newBalance
        db.session.commit()
        return redirect(url_for("core.index"))
    else:
        return "Invalid Request !"


@core.route("allocator")
@login_required
def allocator():
    categoriesList = giveCategoriesListOfDicts()
    return render_template(
        "core/allocator.html",
        categoriesList=categoriesList,
        category="",
        budget="",
    )


@core.route("createCategory", methods=["GET", "POST"])
@login_required
def createCategory():
    if req.method == "GET":
        # Possible only through Redirects to url_for('core.createCategory')
        return redirect(
            url_for("core.allocator")
        )  # category and budget handled by IF jinja syntax in core/allocator.html, same for categoriesList, these values can only be added by render_template, not redirect()
    elif req.method == "POST":
        categoryName = req.form.get("category")
        budget = req.form.get("budget")
        categoriesList = giveCategoriesListOfDicts()

        try:
            
            if int(budget) > current_user.balance:
                flash("You can't Add a Budget Exceeding your Current Balance !", "danger")
                return render_template(
                    "core/allocator.html",
                    categoriesList=categoriesList,
                    category=categoryName,
                    budget="",
                )
                
            
            if categoryName.strip() == "":
                flash("Please Provide a Category name !", "danger")
                return render_template(
                    "core/allocator.html",
                    categoriesList=categoriesList,
                    category="",
                    budget=budget,
                )

            if int(budget) == 0:
                flash("Please Provide a Budget amount !", "danger")
                return render_template(
                    "core/allocator.html",
                    categoriesList=categoriesList,
                    category=categoryName,
                    budget="",
                )
        except (ValueError, TypeError):
            flash("Please provide a Numeric Value for the Budget !", "danger")
            return render_template(
                "core/allocator.html",
                categoriesList=categoriesList,
                category=categoryName,
                budget="",
            )

        categoryName = categoryName.strip()

        userID = current_user.id
        spent = 0
        remaining = budget
        
        current_user.balance -= int(budget)

        categoryObj = Categories(
            userID=userID,
            name=categoryName,
            budget=budget,
            spent=spent,
            remaining=remaining,
        )

        db.session.add(categoryObj)
        db.session.commit()

        flash(f"Successfuly created Category {categoryName} !", "success")
        return redirect(url_for("core.allocator"))

    else:
        return "Invalid Request !"



@core.route("deleteCategory", methods=["GET", "POST"])
@login_required
def deleteCategory():
    if req.method == "GET":
        # Possible only through Redirects to url_for('core.createCategory')
        return render_template('core/deleteCategory.html', categoriesList = giveCategoriesListOfDicts())  # category and budget handled by IF jinja syntax in core/allocator.html, same for categoriesList, these values can only be added by render_template, not redirect()
    elif req.method == "POST":
        categoryName = req.form.get("category")
        categoriesList = giveCategoriesListOfDicts()
   
        try:
            if categoryName.strip() == "":
                flash("Please Provide a Category name !", "danger")
                return render_template(
                    "core/deleteCategory.html",
                    categoriesList=categoriesList,
                    category=""
                )
        except:
            flash("Please Provide Valid Values !", "danger")
            return render_template(
                    "core/deleteCategory.html",
                    categoriesList=categoriesList,
                    category=""
                )

        categoryName = categoryName.strip()

        categoryObj = Categories.query.filter_by(userID = current_user.id, name = categoryName).first()
        amountToBeAdded = categoryObj.budget
        current_user.balance += amountToBeAdded

        db.session.delete(categoryObj)
        db.session.commit()

        flash(f"Successfuly Deleted Category {categoryName}, Refunded ₹{amountToBeAdded} to your monthly Balance !", "success")
        return redirect(url_for("core.index"))

    else:
        return "Invalid Request !"




























@core.route("extend", methods=["GET", "POST"])
@login_required
def extend():
    categoriesList = giveCategoriesListOfDicts()
    if req.method == "GET":
        return render_template(
            "core/extend.html",
            categories=categoriesList,
            category="",
            extension="",
        )
    elif req.method == "POST":

        try:
            category = req.form.get("category")
            extension = int(req.form.get("extension"))
        except (ValueError, TypeError):
            flash("Numeric Value needed !", "danger")
            return render_template(
                "core/extend.html",
                categories=categoriesList,
                category="",
                extension="",
            )


        if extension > current_user.balance:
            flash("Can't Extend beyond your Current Balance !", "danger")
            return render_template(
                "core/extend.html",
                categories=categoriesList,
                category=category,
                extension="",
            )
        

        if not category or category.strip() == "":
            flash("Please Choose a Category !", "danger")
            return render_template(
                "core/extend.html",
                categories=categoriesList,
                category="",
                extension=extension,
            )
        if extension == 0:
            flash("Please Give a Valid Extension amount !", "danger")
            return render_template(
                "core/extend.html",
                categories=categoriesList,
                category=category,
                extension="",
            )

        filteredCategory = Categories.query.filter(
            Categories.name == category, Categories.userID == current_user.id
        ).first()
        # .first() or .all() is ALWAYS needed !!!!!!
        # .all() gives a List of Category Objects ---> all objects are Live Copies from the DB
        # .first() gives a Single Category Object ---> all objects are Live Copies from the DB

        if not filteredCategory:
            flash("Error while fetching category name !", "danger")
            return redirect(url_for("core.allocator"))

        
        filteredCategory.budget += int(extension)
        filteredCategory.remaining += int(extension)
        current_user.balance -= int(extension)

        # db.session.add(filteredCategory) # No need as filteredCategory is a Live Copy of the Row, though
        # db.session.commit() is needed as below
        try:
            db.session.commit()
            flash(
                f"Extended your Budget for {filteredCategory.name} !",
                "success",
            )
            return redirect(url_for("core.allocator"))
        except:
            flash("Some Error Occured !", "danger")
            return redirect(url_for("core.allocator"))
    else:
        return "Invalid Request"




@core.route("reduce", methods=["GET", "POST"])
@login_required
def reduce():
    categoriesList = giveCategoriesListOfDicts()
    if req.method == "GET":
        return render_template(
            "core/reduce.html",
            categories=categoriesList,
            category="",
            reduction="",
        )
    elif req.method == "POST":
        try:
            category = str(req.form.get("category"))
            reduction = int(req.form.get("reduction"))
        except (ValueError, TypeError):
            flash("Numeric Value needed !", "danger")
            return render_template(
                "core/reduce.html",
                categories=categoriesList,
                category="",
                reduction="",
            )


        for c in categoriesList:
            if c['name'] == category:
                targetCategory = c
        

app/templates/core/add.html
{% extends "core/index.html" %} {% block title %} Add Cash {% endblock %} {%
block appName %} Add Cash {% endblock %} {% block mainContent %}
<form action={{url_for('core.add')}} method="POST" class="addCashSection pl-6 pt-6 h-full bg-cardDark rounded-md rounded-t-none">
  <div class="w-[40%] flex flex-col h-full gap-3">
  <p class="text-gray-200 text-[19px]">Enter Cash Amount to Add</p>
  <div>  
    <input min=0 type="number" class="formInput text-white text-[19px]" name="cash" id="cash" placeholder="Cash to Add"/>
</div>

  <div>
    <button type="submit" class=" bg-emerald-600 px-[30px] text-white py-[10px] mt-[22px] border-2 border-white box-border hover:bg-emerald-800 cursor-pointer font-bold text-[17px]">Add Cash</button>
</div>
  
</form>
{% endblock %}

app/templates/core/addExpense.html
{% extends "core/index.html" %} {% block title %} Add Expenses {% endblock %} {%
block appName %} Add Expense to a Category {% endblock %} {% block mainContent %}
<form action="{{url_for('core.addExpense')}}" method="POST" class="addCashSection pl-6 pt-6 h-full bg-cardDark rounded-md rounded-t-none" id="form">
  <div class="w-[40%] flex flex-col h-full gap-3 ">
  <p class="text-gray-200 text-base md:w-full w-[250%] ">Choose Category to add an Expense</p>
  <div>  
    <select name="category" id="category" class="rounded-md text-white border-2 border-white md:w-[130%] w-[220%] p-2.5 value={{category if category else ''}}">
        <option value="" selected disabled hidden>Choose a Category</option>
        {% for c in categoriesList %}
          {% if category == c.name %}
            <option value="{{c.name}}" selected class="bg-[#101828]">{{c.name}}</option>
          {% else %}
            <option value="{{c.name}}" class="bg-[#101828]">{{c.name}}</option>
            {% endif %}
        {% endfor %}
    </select>
    <p class="text-white mt-4 text-base">Money Expent</p>
    <input type="number" name="expense" id="extension" class=" md:w-[130%] w-[220%] formInput mt-2 text-white" min="0" value="{{expense if expense else ''}}">
</div>

  <div>
    <button type="submit" class=" bg-emerald-600 px-[30px] text-white w-[200px] py-2 mt-[10px] border-2 border-white box-border hover:bg-emerald-800 cursor-pointer font-bold text-[17px]">Add Spending</button>
</div>
  
</form>
{% endblock %}

app/templates/core/allocator.html
{% extends 'core/index.html' %} {% block title %} Budget Allocator {% endblock
%} {% block appName %} Budget Allocator{% endblock %} {% block mainContent %}

<div class="flex rounded-md rounded-t-none">
<div class="container flex flex-col mb-[200px] sm:mb-[100px] md:flex-row items-center justify-evenly bg-cardDark w-full rounded-md rounded-t-none">
<form action="{{url_for('core.createCategory')}}" method="POST" class="overflow-hidden h-[300px] min-h-[300px] text-white p-0  w-full md:w-[60%] h-full bg-cardDark rounded-md rounded-t-none " id="form">
  <h3 class="border-b-gray-600 p-[16px] border-b-2 font-bold text-yellow-300">Create a Category and allocate budgets</h3>
  <p class="mb-[4px] mt-[20px] px-[16px]">Category Name</p>
  <input
    type="text"
    name="category"
    id="category"
    class="formInput w-[80%] mb-3 ml-[16px]"
    value = '{{ category if category else "" }}'
  />
  <p class="mb-[4px] px-[16px]">Budget for that category</p>
  <input
    type="number"
    name="budget"
    id="budget"
    min="0"
    class="formInput w-[80%] ml-[16px]"
    value = '{{ budget if budget else "" }}'
    required

  />
  <div>
    <button type="submit" class="authButton w-[80%] mt-4 ml-4 mb-4">
      Create and Allocate 
    </button>
  </div>
</form>
<section class="right flex flex-col w-full justify-between md:border-l-2 md:border-l-gray-600">

  <h3 class="p-[16px] border-b-gray-600  border-b-2 font-bold text-yellow-300 ">Your Categories and Budgets</h3>

        <div class="flex w-full text-left pr-4 border-b-2 border-b-gray-900 justify-between">
              <p class=" w-full text-amber-200 p-[16px] border-r-gray-900 border-r-2 font-bold">Category</p>
              <p class="w-full p-[16px]  text-amber-200 font-bold">Alllocated budget</p>
        </div>

        <div class="text-white h-[140px] min-h-[140px] text-black md:border-r-gray-900 md:border-r-2 overflow-y-scroll bg-gray-700 ">
            {% for category in categoriesList %}
                  <div class="flex w-full border-b-2 border-b-gray-900">
                        <p class="w-full  p-[16px] border-r-2 border-r-gray-900">{{category.name}}</p>
                        <p class="w-full  p-[16px] text-lime-400 font-bold text-xl">₹ {{category.budget}}</p>
                  </div>
            {% endfor %}
        </div>
<div class="extendBtn p-2.5 w-full flex-row sm:flex-col items-center justify-center mb-[0px] bg-transparent justify-center">
  <a href={{url_for('core.extend')}} class="text-white font-bold border-2 border-white p-2 px-8  hover:bg-transparent white  block text-center bg-[#ea0046]  hover:border-[#ea0046] transition duration-300 transition-ease">Extend Budgets</a>
  
  <a href={{url_for('core.reduce')}} class="text-white font-bold border-2 border-white p-2 px-8 block text-center  hover:bg-transparent hover:text-white mt-2.5 block bg-[#00a0f0] hover:border-[#00a0f0] transition duration-300 transition-ease">Reduce Budgets</a>
</div></section>


</div>


<script>
  
</script>
</div>
{% endblock %}

app/templates/core/deleteCategory.html
{% extends "core/index.html" %} {% block title %} Extend Budgets {% endblock %}
{% block appName %} Delete Categories {% endblock %} {% block mainContent %}
<div class="bg-transparent">
  <form
    action="{{url_for('core.deleteCategory')}}"
    method="POST"
    class="addCashSection pl-6 pt-6 h-full bg-cardDark rounded-md rounded-t-none pb-8"
    id="form"
  >
    <div class="w-[40%] flex flex-col h-full gap-3">
      <p class="text-gray-200 text-base w-[170%]">Choose Category to Delete</p>
      <div>
        <select
          name="category"
          id="category"
          class="text-white w-[170%] border-2 border-white p-2.5 value={{category if category else ''}}"
        >
          <option value="" selected disabled hidden class="text-base">
            Choose a Category
          </option>
          {% for c in categoriesList %} {% if category == c.name %}
          <option
            class="text-base"
            value="{{c.name}}"
            selected
            class="bg-[#101828]"
          >
            {{c.name}}
          </option>
          {% else %}
          <option value="{{c.name}}" class="bg-[#101828]">{{c.name}}</option>
          {% endif %} {% endfor %}
        </select>
      </div>

      <button
        type="submit"
        class="bg-red-500 px-[30px] text-white md:py-[10px] py-[8px] md:mt-[10px] mt-[6px] border-2 border-white box-border hover:bg-red-700 cursor-pointer font-bold text-[17px] w-[170%] rounded-md"
      >
        Delete Category
      </button>
    </div>
  </form>
</div>
{% endblock %}

app/templates/core/extend.html
{% extends "core/index.html" %} {% block title %} Add Cash {% endblock %} {%
block appName %} Extend Budgets {% endblock %} {% block mainContent %}
<div class="bg-transparent">
  <form
    action="{{url_for('core.extend')}}"
    method="POST"
    class="addCashSection pl-6 pt-6 h-full bg-cardDark rounded-md rounded-t-none pb-8"
    id="form"
  >
    <div class="w-[40%] flex flex-col h-full gap-3">
      <p class="text-gray-200 text-base w-[170%]">
        Choose Category to Extend Budget
      </p>
      <div>
        <select
          name="category"
          id="category"
          class="text-white w-[170%] border-2 border-white p-2.5 value={{category if category else ''}}"
        >
          <option value="" selected disabled hidden class="text-base">
            Choose a Category
          </option>
          {% for c in categories %} {% if category == c.name %}
          <option
            class="text-base"
            value="{{c.name}}"
            selected
            class="bg-[#101828]"
          >
            {{c.name}}
          </option>
          {% else %}
          <option value="{{c.name}}" class="bg-[#101828]">{{c.name}}</option>
          {% endif %} {% endfor %}
        </select>
        <p class="text-white mt-4 w-[170%]">Extension Amount</p>
        <input
          type="number"
          name="extension"
          id="extension"
          class="formInput mt-2 text-white w-[170%]"
          min="0"
          value="{{extension if extension else ''}}"
        />
      </div>

      <button
        type="submit"
        class="bg-emerald-600 px-[30px] text-white md:py-[10px] py-[8px] md:mt-[10px] mt-[6px] border-2 border-white box-border hover:bg-emerald-800 cursor-pointer font-bold text-[17px] w-[170%] rounded-md"
      >
        Extend Budget
      </button>
    </div>
  </form>
</div>
{% endblock %}

app/templates/core/index.html
    <link
      rel="stylesheet"
      href="{{url_for('static',filename='dist/main.css')}}?v=1.0"
    />
    {% extends "base.html" %}
    {% block title %} Dashboard {% endblock %}

    {% block content %}
    <main class="mainContent bg-gray-900 w-full">
            <div class="card flex flex-col h-[418px] max-h-[418px] w-[90%] sm:w-[50%]">

              <div class="dashboard-heading p-6 text-white text-2xl bg-indigo-700 "style="border-top-left-radius: 0.5rem;
    border-top-right-radius: 0.5rem;">
                {% block appName %}<h1>💰&nbsp;Fundwarden for <span class="font-bold">{{ current_user.name }}</span></h1> {%endblock%}
              </div>

              {% block mainContent %}
              <div class="dashboard-sections flex bg-cardDark h-full w-full rounded-md rounded-t-none">
                <section class="dashboard-section w-full flex flex-col items-start p-5 justify-evenly gap-2 bg-cardDark rounded-md">
                    <h2 class="bg-gray-900 text-white w-full pl-6 p-5 text-xl">Monthly Balance: <span class="text-yellow-500 font-bold text-2xl"> ₹ {{current_user.balance}}</span></h2>
                    <div class="actions flex flex-col gap-2 w-full">
                      <a href={{url_for('core.add')}} class="actionBtn bg-emerald-600 text-white font-bold">Add or Extend Monthly Balance</a>
                      <a href={{url_for('core.tracker')}} class="actionBtn bg-pink-500 text-white font-bold">Expense Tracker</a>
                      <a href={{url_for('core.allocator')}} class="actionBtn bg-purple-600 font-bold text-white">Budget Allocator</a>
                      <a href={{url_for('core.deleteCategory')}} class="actionBtn bg-red-500 font-bold text-white">Delete Categories</a>
                    </div>
                </section>
                
              </div>
              {% endblock %}
            </div>
    </main>

    {% endblock %}
  <script
    src="https://kit.fontawesome.com/a3d72c8bc7.js"
    crossorigin="anonymous"
  ></script>
  <script>
    const handleMenu = () => {
      const navContent = document.getElementById("navContent");
      navContent.classList.toggle("hidden");
    };
  </script>
  <!-- <script src=".../Static/js/script.js"></script> -->
</html>

app/templates/core/reduce.html
{% extends "core/index.html" %} {% block title %} Reduce Budgets {% endblock %}
{% block appName %} Reduce Budgets {% endblock %} {% block mainContent %}
<div class="bg-transparent">
  <form
    action="{{url_for('core.reduce')}}"
    method="POST"
    class="addCashSection pl-6 pt-6 h-full bg-cardDark rounded-md rounded-t-none pb-8"
    id="form"
  >
    <div class="w-[40%] flex flex-col h-full gap-3">
      <p class="text-gray-200 text-base w-[170%]">
        Choose Category to Reduce Budget
      </p>
      <div>
        <select
          name="category"
          id="category"
          class="text-white w-[170%] border-2 border-white p-2.5 value={{category if category else ''}}"
        >
          <option value="" selected disabled hidden class="text-base">
            Choose a Category
          </option>
          {% for c in categories %} {% if category == c.name %}
          <option
            class="text-base"
            value="{{c.name}}"
            selected
            class="bg-[#101828]"
          >
            {{c.name}}
          </option>
          {% else %}
          <option value="{{c.name}}" class="bg-[#101828]">{{c.name}}</option>
          {% endif %} {% endfor %}
        </select>
        <p class="text-white mt-4 w-[170%]">Decrease Amount</p>
        <input
          type="number"
          name="reduction"
          id="reduction"
          class="formInput mt-2 text-white w-[170%]"
          min="0"
          value="{{reduction if reduction else ''}}"
        />
      </div>

      <button
        type="submit"
        class="bg-emerald-600 px-[30px] text-white md:py-[10px] py-[8px] md:mt-[10px] mt-[6px] border-2 border-white box-border hover:bg-emerald-800 cursor-pointer font-bold text-[17px] w-[170%] rounded-md"
      >
        Decrease Budget
      </button>
    </div>
  </form>
</div>
{% endblock %}

app/templates/core/tracker.html
{% extends 'core/index.html' %} {% block title %} Expense Tracker {% endblock %}
{% block appName %}
<h2 class="text-2xl font-bold">Your Expenses</h2>
{% endblock %} {% block mainContent %}

<div class="container h-[400px] max-h-[400px] w-full">
  <section
    class="right w-full bg-cardDark rounded-md rounded-t-none border-l-gray-600 h-full flex flex-col justify-evenly text-tiny grow-1"
  >
    <div class="p-6 pt-0 pb-0 text-white w-full">
      <div class="max-w-4xl mx-auto overflow-y-scroll h-[250px] max-h-[250px]">
        <div
          class="grid md:grid-cols-4 grid-cols-1 bg-black rounded-xl shadow-sm border border-gray-600 overflow-hidden"
        >
          <div
            class="bg-gray-800 text-white px-3 py-2 text-tiny font-semibold uppercase text-yellow-400 hidden md:block"
          >
            Category
          </div>
          <div
            class="bg-gray-800 text-orange-300 px-3 py-2 text-tiny font-semibold uppercase text-orange-400 hidden md:block"
          >
            Budget
          </div>
          <div
            class="bg-gray-800 px-3 py-2 text-tiny font-semibold text-red-400 uppercase hidden md:block"
          >
            Spent
          </div>
          <div
            class="bg-gray-800 px-3 py-2 text-tiny font-semibold text-emerald-400 uppercase hidden md:block"
          >
            Remaining
          </div>

          {% for cat in categoriesList %}
          <div
            class="px-3 py-2 border-b border-gray-500 bg-gray-700 flex items-center"
          >
            <div
              class="text-yellow-400 px-3 py-2 text-tiny uppercase font-semibold md:hidden block bg-gray-800 mr-3"
            >
              Category
            </div>

            <span
              class="font-bold text-white inline-block max-w-[20ch] break-all text-base"
              >{{ cat.name }}</span
            >
          </div>

          <div
            class="font-bold px-3 py-4 border-b border-gray-500 bg-gray-700 text-white flex items-center"
          >
            <div
              class="text-orange-400 px-3 py-2 text-tiny uppercase font-semibold md:hidden block bg-gray-800 mr-3"
            >
              Budget
            </div>

            <span
              class="font-bold text-white inline-block max-w-[20ch] break-all text-base"
              >₹{{ "{:,}".format(cat.budget) }}</span
            >
          </div>

          <div
            class="px-3 py-4 border-b border-gray-500 bg-gray-700 text-red-400 font-bold flex items-center"
          >
            <div
              class="text-text-400 px-3 py-2 text-tiny uppercase font-semibold md:hidden block bg-gray-800 mr-3"
            >
              Spent
            </div>
            <span
              class="font-bold text-red-400 inline-block max-w-[20ch] break-all text-base"
              >₹{{ "{:,}".format(cat.spent) }}</span
            >
          </div>

          <div
            class="px-3 py-4 border-b border-gray-500 bg-gray-700 text-emerald-400 font-bold flex items-center mb-6 md:mb-0"
          >
            <div
              class="text-emerald-400 px-3 py-2 text-tiny uppercase font-semibold md:hidden block bg-gray-800 mr-3"
            >
              Remaining
            </div>
            <span
              class="font-bold text-emerald-400 inline-block max-w-[20ch] break-all text-base"
              >₹{{ "{:,}".format(cat.budget - cat.spent) }}</span
            >
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="extendBtn flex items-center justify-center h-auto">
      <a
        href="{{url_for('core.addExpense')}}"
        class="text-yellow-300 bg-transparent text-red-400 px-3 py-2 text-tiny uppercase font-semibold block bg-gray-800 font-bold border-2 border-white p-2 px-8 bg-transparent hover:bg-yellow-300 hover:border-yellow-300 hover:text-black"
        >Add a Spending</a
      >
    </div>
  </section>
</div>

{% endblock %}